$timestamp = Get-Date -Format "yyyyMMddHHmmss"
$username = "e2e_pref_once_$timestamp"
$password = "123456"

Write-Host "============================================"
Write-Host "UI自测流程 - 手动步骤记录"
Write-Host "============================================"
Write-Host "测试用户: $username"
Write-Host "测试密码: $password"
Write-Host ""
Write-Host "[STEP 1] 打开浏览器访问 http://127.0.0.1:8080"
Start-Process "http://127.0.0.1:8080"
Write-Host "[STEP 2] 请手动注册用户: $username / $password"
Write-Host "[STEP 3] 登录后若出现定位授权弹层，点击'不允许'"
Write-Host "[STEP 4] 验证偏好问卷弹层#prefModal是否出现"
Write-Host "[STEP 5] 完成问卷并提交，确认弹层关闭"
Write-Host "[STEP 6] 打开 http://127.0.0.1:8080/assets/location.html"
Write-Host "         点击'返回聊天'或直接刷新首页"
Write-Host "[STEP 7] 验证偏好问卷是否再次弹出"
Write-Host ""
Write-Host "请手动执行以上步骤并记录结果"
Write-Host "============================================"
